name: Build Android APK with Buildozer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get dependencies
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
